name: contacts_list
description: A contacts list flutter app - POC

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4
  flutter_modular: ^4.5.0
  cupertino_icons: ^1.0.2
  sticky_headers: ^0.2.0
  rxdart: ^0.27.3
  json_serializable: ^6.1.5
  json_annotation: ^4.4.0
  dio: ^4.0.4
  azlistview: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  mobx_codegen: ^2.0.5+2
  build_runner: ^2.1.8
  flutter_lints: ^1.0.0
  modular_test: ^1.0.1+1

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/

scripts:
  runner: fvm flutter pub run build_runner build --delete-conflicting-outputs
  watch_runner: fvm flutter pub run build_runner watch --delete-conflicting-outputs
